"""
Django settings for Bocar project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables de entorno definidas en el archivo .env (en la raíz del
# proyecto). Si el archivo no existe, no falla: se usan los valores por defecto
# o las variables ya presentes en el entorno del sistema.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(vqc^5z*8pm144^irjaoji7y^z35q^h00ri(oja5ae&e=8g#2)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
    'djoser',
    'RFQ_Mold',
    'RFQ_Trimming',
    'Proveedores',
    'General_RFQs',
    'Asignaciones',
    'Prov_RFQ_Mold',
    'Prov_RFQ_Trimming',
    'Comercializacion',
    'Industrializacion',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_countries',
    'notificaciones',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.CookieJWTAuthentication',
    ),
}

DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True, # Pide confirmar la contraseña al registrarse
    'PERMISSIONS': {
        'user_create': ['rest_framework.permissions.IsAdminUser'],
        'user_list': ['rest_framework.permissions.IsAdminUser'],
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15), # El token de uso diario
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=10),    # El token para renovar
    'ROTATE_REFRESH_TOKENS':  True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',), 
    'TOKEN_OBTAIN_SERIALIZER': "users.serializers.CustomTokenObtainPairSerializer",              # Para usar "Bearer <token>"
}

# Configuración de cookies
COOKIE_SECURE   = not DEBUG   # True en producción (HTTPS), False en desarrollo
COOKIE_SAMESITE = 'Lax'    

SPECTACULAR_SETTINGS = {
    'TITLE': 'API SWAGGER FOR BOCAR',

    'DESCRIPTION': '''Este es el API Swagger para el proyecto Bocar,
    que incluye endpoints para la gestión de RFQs de moldes y recortes, 
    así como autenticación de usuarios.''',

    'VERSION': '1.0.0',
    
    'SERVE_INCLUDE_SCHEMA': False,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Bocar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Bocar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'users.CustomUser'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ---------------------------------------------------------------------------
# Email — Microsoft 365 (Office 365)
# El backend se controla por la variable de entorno EMAIL_BACKEND.
# Desarrollo (default): consola — los correos se imprimen, no se envían.
# Producción: definir EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
# junto con las variables BOCAR_EMAIL_USER y BOCAR_EMAIL_PASSWORD.
# ---------------------------------------------------------------------------
EMAIL_BACKEND       = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST          = 'smtp.office365.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = os.environ.get('BOCAR_EMAIL_USER', 'CORREO@DOMINIO.COM')
EMAIL_HOST_PASSWORD = os.environ.get('BOCAR_EMAIL_PASSWORD', '')
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER

# ---------------------------------------------------------------------------
# Celery — broker Redis
# ---------------------------------------------------------------------------
CELERY_BROKER_URL        = os.environ.get('CELERY_BROKER_URL', 'amqp://guest:guest@localhost:5672//')
CELERY_RESULT_BACKEND    = 'rpc://'
CELERY_ACCEPT_CONTENT    = ['json']
CELERY_TASK_SERIALIZER   = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE          = TIME_ZONE



# ---------------------------------------------------------------------------
# Flag de envío de correos — controlado por variable de entorno.
# Permite activar/desactivar las notificaciones durante los tests sin tocar
# código ni depender del broker de Celery. Acepta: True / true / 1 / yes.
# Temporal: se eliminará cuando el servicio de correos quede activado de forma
# permanente en producción.
# ---------------------------------------------------------------------------
NOTIFICATIONS_ENABLED = os.environ.get('NOTIFICATIONS_ENABLED', 'False').lower() in ('true', '1', 'yes')