"""
Django settings for Bocar project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga las variables de entorno definidas en el archivo .env (en la raíz del
# proyecto). Si el archivo no existe, no falla: se usan los valores por defecto
# o las variables ya presentes en el entorno del sistema.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Loaded from .env — crashes at startup if missing (never deploy without it)
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # Habilita django-cors-headers para que el backend pueda responder solicitudes CORS del frontend.
    'rest_framework',
    'users',
    'djoser',
    'RFQ_Mold',
    'RFQ_Trimming',
    'Proveedores',
    'General_RFQs',
    'Asignaciones',
    'Prov_RFQ_Mold',
    'Prov_RFQ_Trimming',
    'Comercializacion',
    'Industrializacion',
    'modulo_IA',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_countries',
    'notificaciones',
    'historial',
    'chatbot',
    'Evaluaciones',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
    },
}

DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True, # Pide confirmar la contraseña al registrarse
    'PERMISSIONS': {
        'user_create': ['users.permissions.IsAdminUser'],
        'user_list': ['users.permissions.IsAdminUser'],
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15), # El token de uso diario
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=10),    # El token para renovar
    'ROTATE_REFRESH_TOKENS':  True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',), 
    'TOKEN_OBTAIN_SERIALIZER': "users.serializers.CustomTokenObtainPairSerializer",              # Para usar "Bearer <token>"
}

# Configuración de cookies
COOKIE_SECURE   = not DEBUG   # True en producción (HTTPS), False en desarrollo
COOKIE_SAMESITE = 'Lax'    

SPECTACULAR_SETTINGS = {
    'TITLE': 'API SWAGGER FOR BOCAR',

    'DESCRIPTION': '''Este es el API Swagger para el proyecto Bocar,
    que incluye endpoints para la gestión de RFQs de moldes y recortes, 
    así como autenticación de usuarios.''',

    'VERSION': '1.0.0',
    
    'SERVE_INCLUDE_SCHEMA': False,
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]
CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
]
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'Bocar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Bocar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ---------------------------------------------------------------------------
# Base de datos — Microsoft SQL Server (producción)
# Requiere: pip install mssql-django pyodbc
# y Microsoft ODBC Driver for SQL Server 18 instalado en el sistema.
# Para activar: comentar el bloque SQLite de arriba y descomentar este.
# ---------------------------------------------------------------------------
# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'NAME':     os.environ.get('DB_NAME', 'bocar_db'),
#         'HOST':     os.environ.get('DB_HOST', 'localhost'),
#         'PORT':     os.environ.get('DB_PORT', '1433'),
#         'USER':     os.environ.get('DB_USER', ''),
#         'PASSWORD': os.environ.get('DB_PASSWORD', ''),
#         'OPTIONS': {
#             'driver':            os.environ.get('DB_DRIVER', 'ODBC Driver 18 for SQL Server'),
#             'TrustServerCertificate': os.environ.get('DB_TRUST_SERVER_CERT', 'yes'),
#         },
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'users.CustomUser'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------------------
# File upload limits
# ---------------------------------------------------------------------------
MAX_UPLOAD_SIZE_MB       = int(os.environ.get('MAX_UPLOAD_SIZE_MB', 100))
MAX_FILES_PER_REQUEST    = int(os.environ.get('MAX_FILES_PER_REQUEST', 10))
DATA_UPLOAD_MAX_MEMORY_SIZE  = MAX_UPLOAD_SIZE_MB * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE  = MAX_UPLOAD_SIZE_MB * 1024 * 1024

# ---------------------------------------------------------------------------
# Email — Microsoft 365 (Office 365)
# El backend se controla por la variable de entorno EMAIL_BACKEND.
# Desarrollo (default): consola — los correos se imprimen, no se envían.
# Producción: definir EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
# junto con las variables BOCAR_EMAIL_USER y BOCAR_EMAIL_PASSWORD.
# ---------------------------------------------------------------------------
EMAIL_BACKEND       = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST          = 'smtp.office365.com'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = os.environ.get('BOCAR_EMAIL_USER', 'CORREO@DOMINIO.COM')
EMAIL_HOST_PASSWORD = os.environ.get('BOCAR_EMAIL_PASSWORD', '')
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER

# ---------------------------------------------------------------------------
# Celery — broker Redis
# ---------------------------------------------------------------------------
CELERY_BROKER_URL        = os.environ.get('CELERY_BROKER_URL', 'amqp://guest:guest@localhost:5672//')
CELERY_RESULT_BACKEND    = 'rpc://'
CELERY_ACCEPT_CONTENT    = ['json']
CELERY_TASK_SERIALIZER   = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE          = TIME_ZONE



# ---------------------------------------------------------------------------
# Flag de envío de correos — controlado por variable de entorno.
# Permite activar/desactivar las notificaciones durante los tests sin tocar
# código ni depender del broker de Celery. Acepta: True / true / 1 / yes.
# Temporal: se eliminará cuando el servicio de correos quede activado de forma
# permanente en producción.
# ---------------------------------------------------------------------------
NOTIFICATIONS_ENABLED = os.environ.get('NOTIFICATIONS_ENABLED', 'False').lower() in ('true', '1', 'yes')

# ---------------------------------------------------------------------------
# Chatbot / LLM
# LLM_BACKEND: 'gemini' (default) | 'local' (Ollama en localhost)
# ---------------------------------------------------------------------------
LLM_BACKEND   = os.environ.get('LLM_BACKEND', 'gemini')
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '')
GEMINI_MODEL   = os.environ.get('GEMINI_MODEL', 'gemini-2.0-flash')
LOCAL_LLM_URL  = os.environ.get('LOCAL_LLM_URL', 'http://localhost:11434')
LOCAL_LLM_MODEL = os.environ.get('LOCAL_LLM_MODEL', 'llama3.2')
