# Generated by Django 6.0.5 on 2026-05-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SinRol', 'Sin Rol Asignado'), ('Ind', 'Industrialización'), ('Com', 'Comercialización'), ('Pro', 'Proveedor')], default='SinRol', max_length=10, verbose_name='Role'),
        ),
    ]
