# Generated by Django 6.0.4 on 2026-06-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SinRol', 'Sin Rol Asignado'), ('Ind', 'Industrialización'), ('Com', 'Comercialización'), ('Pro', 'Proveedor'), ('IT', 'Sistemas')], default='SinRol', max_length=10, verbose_name='Role'),
        ),
    ]
