# Generated by Django 5.2.15 on 2026-06-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prov_RFQ_Trimming', '0002_cost_breakdown_trimming_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_breakdown_trimming',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
