# Generated by Django 5.2.15 on 2026-06-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prov_RFQ_Trimming', '0003_alter_cost_breakdown_trimming_id_alter_list_id'),
        ('Prov_RFQ_Trimming', '0003_cost_breakdown_trimming_file'),
    ]

    operations = [
    ]
