# Generated by Django 5.2.15 on 2026-06-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prov_RFQ_Trimming', '0004_merge_20260612_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_breakdown_trimming',
            name='ctbd',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='cost_breakdown_trimming_file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
