# Generated by Django 6.0.4 on 2026-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prov_RFQ_Mold', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_breakdown_mold',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado')], default='draft', max_length=10),
        ),
    ]
