# Generated by Django 6.0.5 on 2026-06-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prov_RFQ_Mold', '0002_cost_breakdown_mold_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Breakdown_Mold_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='Files/Cost_Breakdown_Mold/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('id_cost_breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='Prov_RFQ_Mold.cost_breakdown_mold')),
            ],
            options={
                'db_table': 'Cost_Breakdown_Mold_File',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
