# Generated by Django 6.0.5 on 2026-06-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prov_RFQ_Mold', '0003_cost_breakdown_mold_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_breakdown_mold',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cost_breakdown_mold',
            name='ctbd',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cost_breakdown_mold',
            name='max_weight_for_mold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cost_breakdown_mold',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
