# Generated by Django 6.0.2 on 2026-06-09 01:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '0005_alter_proveedor_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion_tipo', models.CharField(choices=[('mold', 'Mold'), ('trimming', 'Trimming')], max_length=10)),
                ('asignacion_id', models.PositiveIntegerField()),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('fue_puntual', models.BooleanField(default=False)),
                ('dias_diferencia', models.IntegerField(default=0)),
                ('solicito_extension', models.BooleanField(default=False)),
                ('cotizacion_enviada', models.BooleanField(default=False)),
                ('calidad_cotizacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comunicacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentarios', models.TextField(blank=True, default='')),
                ('score', models.FloatField(default=0.0)),
                ('evaluado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='Proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Evaluación de Proveedor',
                'verbose_name_plural': 'Evaluaciones de Proveedores',
                'db_table': 'Evaluacion_Proveedor',
                'ordering': ['-fecha_evaluacion'],
                'unique_together': {('asignacion_tipo', 'asignacion_id')},
            },
        ),
    ]
