# Generated by Django 6.0.4 on 2026-05-16 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ_Trimming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('En_Ind', 'En Industrialización'), ('En_Com', 'En Comercialización'), ('En_Pro', 'En Proveedor')], default='En_Ind', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('complete', models.BooleanField(default=False)),
                ('logical_delete', models.BooleanField(default=False)),
                ('DESC', models.CharField(default='', max_length=255)),
                ('PPY', models.FloatField(default=0.0)),
                ('CUST', models.CharField(default='', max_length=100)),
                ('PNUM', models.CharField(default='', max_length=100)),
                ('PRLF', models.FloatField(default=0.0)),
                ('DTQ', models.DateField(blank=True, null=True)),
                ('press', models.CharField(blank=True, max_length=100)),
                ('no_of_cavities', models.IntegerField(blank=True, null=True)),
                ('no_of_hydraulic_slides', models.CharField(blank=True, help_text='Defined by toolmaker', max_length=100)),
                ('fully_automatic_process', models.CharField(blank=True, max_length=100)),
                ('presence_detectors', models.CharField(blank=True, max_length=100)),
                ('trimming_process_condition', models.CharField(blank=True, max_length=100)),
                ('admissible_residual_burr_mm', models.FloatField(blank=True, null=True)),
                ('castings_supplied_by_auma', models.CharField(blank=True, max_length=100)),
                ('adjustments_optimization_at_tool', models.CharField(blank=True, max_length=100)),
                ('gas_springs', models.CharField(blank=True, help_text='Defined by toolmaker', max_length=100)),
                ('di_design_3d_model', models.BooleanField(default=False)),
                ('di_design_3d_model_note', models.CharField(blank=True, default='', max_length=250)),
                ('di_design_2d_data', models.BooleanField(default=False)),
                ('di_design_2d_data_note', models.CharField(blank=True, default='', max_length=250)),
                ('di_punch_pins_data', models.BooleanField(default=False)),
                ('di_punch_pins_data_note', models.CharField(blank=True, default='', max_length=250)),
                ('di_manufacturing_proposals', models.BooleanField(default=False)),
                ('di_manufacturing_proposals_note', models.CharField(blank=True, default='', max_length=250)),
                ('di_latest_trim_die_improvements', models.BooleanField(default=False)),
                ('di_latest_trim_die_improvements_note', models.CharField(blank=True, default='', max_length=250)),
                ('di_sketch_trim_die_concept', models.BooleanField(default=False)),
                ('di_sketch_trim_die_concept_note', models.CharField(blank=True, default='', max_length=250)),
                ('di_trim_die_no1', models.BooleanField(default=False)),
                ('di_trim_die_no1_note', models.CharField(blank=True, default='', max_length=250)),
                ('di_trim_die_no2', models.BooleanField(default=False)),
                ('di_trim_die_no2_note', models.CharField(blank=True, default='', max_length=250)),
                ('di_set_of_spare_parts', models.BooleanField(default=False)),
                ('di_set_of_spare_parts_note', models.CharField(blank=True, default='', max_length=250)),
                ('di_hydraulic_cylinders_limit_sw', models.BooleanField(default=False)),
                ('di_hydraulic_cylinders_limit_sw_note', models.CharField(blank=True, default='', max_length=250)),
                ('oi_frame_refurbishment', models.BooleanField(default=False)),
                ('oi_set_of_electric_wires', models.BooleanField(default=False)),
                ('oi_others', models.CharField(blank=True, default='', max_length=255)),
                ('oi_delivery_date_imex', models.DateField(blank=True, null=True)),
                ('oi_ejector_system_fixed_side', models.CharField(blank=True, default='', max_length=100)),
                ('part_name', models.CharField(blank=True, default='', max_length=255)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('part_dim_length_mm', models.FloatField(blank=True, null=True)),
                ('part_dim_width_mm', models.FloatField(blank=True, null=True)),
                ('part_dim_height_mm', models.FloatField(blank=True, null=True)),
                ('min_wall_thickness_mm', models.FloatField(blank=True, null=True)),
                ('max_wall_thickness_mm', models.FloatField(blank=True, null=True)),
                ('projected_area_cm2', models.FloatField(blank=True, null=True)),
                ('surface_cm2', models.FloatField(blank=True, null=True)),
                ('volume_cm3', models.FloatField(blank=True, null=True)),
                ('gross_weight_g', models.FloatField(blank=True, null=True)),
                ('press_type', models.CharField(blank=True, max_length=100)),
                ('introduction_extraction_process', models.CharField(blank=True, max_length=100)),
                ('biscuit_position', models.CharField(blank=True, max_length=100)),
                ('quantity_of_punch_pins', models.CharField(blank=True, help_text='Número o Defined by toolmaker', max_length=100)),
                ('temperature_when_trimmed', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_trimmings_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
