# Generated by Django 6.0.4 on 2026-05-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ_Trimming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfq_trimming',
            options={'verbose_name': 'RFQ Trimming', 'verbose_name_plural': 'RFQs Trimming'},
        ),
        migrations.AlterModelTable(
            name='rfq_trimming',
            table='RFQ_Trimming',
        ),
    ]
