# Generated by Django 6.0.4 on 2026-05-21 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ_Trimming', '0002_alter_rfq_trimming_options_alter_rfq_trimming_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfq_trimming',
            options={'ordering': ['-created_date'], 'verbose_name': 'RFQ Trimming', 'verbose_name_plural': 'RFQs Trimming'},
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='CUST',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='DESC',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='PNUM',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='adjustments_optimization_at_tool',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='biscuit_position',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='castings_supplied_by_auma',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='fully_automatic_process',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='gas_springs',
            field=models.CharField(blank=True, default='', help_text='Defined by toolmaker', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='introduction_extraction_process',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='no_of_hydraulic_slides',
            field=models.CharField(blank=True, default='', help_text='Defined by toolmaker', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='part_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='presence_detectors',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='press',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='press_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='quantity_of_punch_pins',
            field=models.CharField(blank=True, default='', help_text='Número o Defined by toolmaker', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='temperature_when_trimmed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='trimming_process_condition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='RFQ_Trimming_EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trimming_edit_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trimming_edit_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('rfq_trimming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='RFQ_Trimming.rfq_trimming')),
            ],
            options={
                'verbose_name': 'Solicitud de Edición Trimming',
                'verbose_name_plural': 'Solicitudes de Edición Trimming',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQ_Trimming_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='rfq_trimming/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rfq_trimming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='RFQ_Trimming.rfq_trimming')),
            ],
            options={
                'verbose_name': 'Archivo RFQ Trimming',
                'verbose_name_plural': 'Archivos RFQ Trimming',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
