# Generated by Django 6.0.4 on 2026-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ_Trimming', '0003_alter_rfq_trimming_options_alter_rfq_trimming_cust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq_trimming_file',
            name='archivo',
            field=models.FileField(upload_to='Files/RFQ_Trimming/'),
        ),
    ]
