# Generated by Django 6.0.5 on 2026-06-09 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0005_alter_proveedor_rating'),
        ('RFQ_Trimming', '0004_alter_rfq_trimming_file_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq_trimming',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_trimmings_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='closure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='selected_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_trimmings_selected', to='Proveedores.proveedor'),
        ),
    ]
