# Generated by Django 6.0.5 on 2026-06-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ_Trimming', '0008_remove_rfq_trimming_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq_trimming',
            name='part_dim_height_mm',
        ),
        migrations.RemoveField(
            model_name='rfq_trimming',
            name='part_dim_width_mm',
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='oi_delivery_date_imex_applies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='oi_ejector_fixed_applies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='oi_ejector_fixed_note',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='oi_frame_refurbishment_note',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='oi_others_applies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='oi_set_of_electric_wires_note',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='part_dimension',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='previous_job',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rfq_trimming',
            name='punch_pins_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rfq_trimming',
            name='no_of_cavities',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
