# Generated by Django 6.0.4 on 2026-05-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ_Mold', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq_mold',
            name='No_CAV',
            field=models.CharField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='No_ofHS',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='No_ofMS',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='ThirdPSupp',
            field=models.CharField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='number_of_gates_per_part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='number_of_parts_per_stroke',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='number_of_tools',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
