# Generated by Django 6.0.4 on 2026-05-19 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ_Mold', '0002_alter_rfq_mold_no_cav_alter_rfq_mold_no_ofhs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfq_mold',
            options={'ordering': ['-created_date'], 'verbose_name': 'RFQ Mold', 'verbose_name_plural': 'RFQ Molds'},
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='CUST',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='DESC',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='ELAB',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='No_CAV',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='No_ofHS',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='No_ofMS',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='PNUM',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='PT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='TT',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='ThirdPSupp',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_molds_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='number_of_gates_per_part',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='number_of_parts_per_stroke',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rfq_mold',
            name='number_of_tools',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RFQ_Mold_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='rfq_mold/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rfq_mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='RFQ_Mold.rfq_mold')),
            ],
            options={
                'verbose_name': 'Archivo RFQ Mold',
                'verbose_name_plural': 'Archivos RFQ Mold',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
