# Generated by Django 6.0.4 on 2026-05-21 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ_Mold', '0003_alter_rfq_mold_options_alter_rfq_mold_cust_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ_Mold_EditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mold_edit_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mold_edit_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('rfq_mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='RFQ_Mold.rfq_mold')),
            ],
            options={
                'verbose_name': 'Solicitud de Edición Mold',
                'verbose_name_plural': 'Solicitudes de Edición Mold',
                'ordering': ['-requested_at'],
            },
        ),
    ]
