# Generated by Django 6.0.4 on 2026-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ_Mold', '0004_rfq_mold_editrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq_mold_file',
            name='archivo',
            field=models.FileField(upload_to='Files/RFQ_Mold/'),
        ),
    ]
