# Generated by Django 6.0.5 on 2026-06-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFQ_Mold', '0006_rfq_mold_closed_at_rfq_mold_closed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq_mold',
            name='selected_supplier',
        ),
    ]
