# Generated by Django 6.0.4 on 2026-05-27 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '0005_alter_proveedor_rating'),
        ('RFQ_Mold', '0005_alter_rfq_mold_file_archivo'),
        ('RFQ_Trimming', '0004_alter_rfq_trimming_file_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_Proveedor_Mold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_asignacion', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_answered', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('logical_delete', models.BooleanField(default=False)),
                ('id_Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_mold', to='Proveedores.proveedor')),
                ('id_RFQ_Mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='RFQ_Mold.rfq_mold')),
                ('id_user_comercializacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_mold', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación Proveedor Mold',
                'verbose_name_plural': 'Asignaciones Proveedor Mold',
                'db_table': 'Asignacion_Proveedor_Mold',
            },
        ),
        migrations.CreateModel(
            name='Asignacion_Proveedor_Trimming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_asignacion', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_answered', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('logical_delete', models.BooleanField(default=False)),
                ('id_Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_trimming', to='Proveedores.proveedor')),
                ('id_RFQ_Trimming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='RFQ_Trimming.rfq_trimming')),
                ('id_user_comercializacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_trimming', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación Proveedor Trimming',
                'verbose_name_plural': 'Asignaciones Proveedor Trimming',
                'db_table': 'Asignacion_Proveedor_Trimming',
            },
        ),
    ]
