# Generated by Django 6.0.4 on 2026-06-01 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asignaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudExtensionMold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('nueva_fecha', models.DateField()),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=10)),
                ('solicitada_at', models.DateTimeField(auto_now_add=True)),
                ('revisada_at', models.DateTimeField(blank=True, null=True)),
                ('id_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_extension', to='Asignaciones.asignacion_proveedor_mold')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensiones_mold_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Extensión Mold',
                'verbose_name_plural': 'Solicitudes de Extensión Mold',
                'db_table': 'Solicitud_Extension_Mold',
            },
        ),
        migrations.CreateModel(
            name='SolicitudExtensionTrimming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('nueva_fecha', models.DateField()),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=10)),
                ('solicitada_at', models.DateTimeField(auto_now_add=True)),
                ('revisada_at', models.DateTimeField(blank=True, null=True)),
                ('id_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_extension', to='Asignaciones.asignacion_proveedor_trimming')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensiones_trimming_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Extensión Trimming',
                'verbose_name_plural': 'Solicitudes de Extensión Trimming',
                'db_table': 'Solicitud_Extension_Trimming',
            },
        ),
    ]
