# Generated by Django 6.0.5 on 2026-06-03 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_tipo', models.CharField(choices=[('mold', 'Mold'), ('trimming', 'Trimming')], max_length=10)),
                ('rfq_id', models.PositiveIntegerField()),
                ('evento', models.CharField(choices=[('CREACION', 'RFQ creada'), ('EDICION', 'RFQ editada'), ('ENVIO_COMERCIALIZACION', 'Enviada a Comercialización'), ('ENVIO_PROVEEDORES', 'Enviada a Proveedores'), ('ASIGNACION_PROVEEDORES', 'Proveedores asignados'), ('SOLICITUD_EDICION', 'Solicitud de edición'), ('EDICION_APROBADA', 'Solicitud de edición aprobada'), ('EDICION_RECHAZADA', 'Solicitud de edición rechazada'), ('COTIZACION_RECIBIDA', 'Cotización recibida'), ('CANCELACION', 'RFQ cancelada'), ('EXTENSION_SOLICITADA', 'Extensión de tiempo solicitada'), ('EXTENSION_APROBADA', 'Extensión de tiempo aprobada'), ('EXTENSION_RECHAZADA', 'Extensión de tiempo rechazada')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_anterior', models.CharField(blank=True, default='', max_length=20)),
                ('status_nuevo', models.CharField(blank=True, default='', max_length=20)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de historial RFQ',
                'verbose_name_plural': 'Historial de RFQs',
                'db_table': 'RFQ_Historial',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['rfq_tipo', 'rfq_id'], name='RFQ_Histori_rfq_tip_00db23_idx')],
            },
        ),
    ]
