# Generated by Django 6.0.4 on 2026-06-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfqhistorial',
            name='evento',
            field=models.CharField(choices=[('CREACION', 'RFQ creada'), ('EDICION', 'RFQ editada'), ('ENVIO_COMERCIALIZACION', 'Enviada a Comercialización'), ('ENVIO_PROVEEDORES', 'Enviada a Proveedores'), ('ASIGNACION_PROVEEDORES', 'Proveedores asignados'), ('SOLICITUD_EDICION', 'Solicitud de edición'), ('EDICION_APROBADA', 'Solicitud de edición aprobada'), ('EDICION_RECHAZADA', 'Solicitud de edición rechazada'), ('COTIZACION_RECIBIDA', 'Cotización recibida'), ('CANCELACION', 'RFQ cancelada'), ('EXTENSION_SOLICITADA', 'Extensión de tiempo solicitada'), ('EXTENSION_APROBADA', 'Extensión de tiempo aprobada'), ('EXTENSION_RECHAZADA', 'Extensión de tiempo rechazada'), ('EVALUACION_PROVEEDOR', 'Proveedor evaluado por Compras'), ('CIERRE_RFQ', 'RFQ cerrada formalmente')], max_length=30),
        ),
    ]
