# Generated by Django 6.0.4 on 2026-05-20 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=100)),
                ('continente', models.CharField(choices=[('NA', 'North America'), ('LA', 'Latin America'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('OC', 'Oceania')], max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('id_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Proveedores',
            },
        ),
    ]
