# Generated by Django 6.0.4 on 2026-05-20 17:13

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0002_alter_proveedor_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre_empresa',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='email_contacto',
            new_name='contact_email',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='continente',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='pais',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='continent',
            field=models.CharField(choices=[('NA', 'North America'), ('LA', 'Latin America'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('OC', 'Oceania')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='country',
            field=django_countries.fields.CountryField(default='NA', max_length=2),
        ),
    ]
