# Generated by Django 6.0.4 on 2026-05-20 17:17

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0003_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
