# Generated by Django 6.0.4 on 2026-05-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0004_alter_proveedor_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
